### ISSUE TITLE
Cambiar el link del logo de Tepa del header.

### ISSUE THREAD

**Issue by mikemotion** [krrrunch/consulta-tepa#25]
Hay que cambiar el logo de tepa del header para que mande a Home.

Yo había indicado que este mandara a la página de Tepa pero utilizando la página resulta que cuando estamos en la sección de la consulta, esto genera confusión pues uno esperaría poder regresar a home.

Dejar el enlace del logo de tepa del footer así cómo está.

**Comment by memiux** [comment]
Cada template físico tiene su propia barra de navegación [home.php](https://github.com/krrrunch/consulta-tepa/blob/ca6f5352e0d20e181a7ba4e74d5dfbcc388ec6e8/public/site/templates/home.php#L5), [consulta.php](https://github.com/krrrunch/consulta-tepa/blob/ca6f5352e0d20e181a7ba4e74d5dfbcc388ec6e8/public/site/templates/consulta.php#L10).
Así que se puede dejar home a tepa.gob y `/consulta` a `/` (home)
#Trends2016 😏

**Comment by mikemotion** [comment]
Hay que dejar los dos a home por consistencia en la navegación.
