### ISSUE TITLE
Corregir nombre de Parábola Arquitectos

### ISSUE THREAD

**Issue by mikemotion** [krrrunch/consulta-tepa#28]
Actualmente está incorrectamente cómo "Parábola Aquitectos" la forma correcta es "Parábola Arquitectos"

**Comment by memiux** [comment]
```diff
-Parábola Aquitectos
+Parábola Arquitectos
```

\`\`\`diff
-Parábola Aquitectos
+Parábola Arquitectos
\`\`\`
